name: Coding Standards
on: [push, pull_request]
jobs:
  coding-standards:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
      - name: Code style checks for PHP
        run: |
          composer install
          composer lint-all
