name: Coding Standards
on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - 'composer.*'
jobs:
  coding-standards:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
      - name: Code style checks for PHP
        run: |
          composer update
          composer lint-all
