name: CycloneDX PHP Composer Generate SBOM
on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
      - 'composer.*'
jobs:
  sbom:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
    steps:
      - uses: CycloneDX/gh-php-composer-generate-sbom@v1.0.0

