name: Test Current Directory Plugin Install

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '5 * * * *'

jobs:
  test-install:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
        wordpress-versions: ['5.8', '5.9']
        experimental: [false]
        # Uncomment for testing other experimental version combinations
        # include:
        #   - php-versions: '8.2'
        #     wordpress-versions: '5.9'
        #     experimental: true
    env:
      DB_HOST: 127.0.0.1
      DB_DATABASE: wp
      DB_USER: wp
      DB_PASSWORD: wp
      WPROOT: /var/www/html/wordpress
    services:
      database:
        image: mariadb:10.7
        env:
          MARIADB_DATABASE: $DB_DATABASE
          MARIADB_USER: $DB_USER
          MARIADB_PASSWORD: $DB_PASSWORD
          MARIADB_RANDOM_ROOT_PASSWORD: yes
        ports:
          - 3306
        # Set health checks to wait until database has started
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, mbstring, mysqli, zip
      - name: Install WP-CLI
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          mv wp-cli.phar /usr/local/bin/wp
      - name: Create Directory
        run: |
          id
          sudo mkdir -p $WPROOT
          sudo chmod a+wrx $WPROOT
          ls -al $WPROOT
      - name: Download WordPress
        run: >
          wp core download
          --path=$WPROOT
          --version=${{ matrix.wordpress-versions }}
          --force
      - name: Configure WordPress
        run: >
          wp config create
          --path=$WPROOT
          --allow-root
          --dbhost=$DB_HOST
          --dbname=$DB_DATABASE
          --dbuser=$DB_USER
          --dbpass=$DB_PASSWORD
          --force
      - name: Install WordPress
        run: >
          wp core install
          --path=$WPROOT
          --allow-root
          --url=localhost
          --title=WP
          --admin_user=admin
          --admin_email=example@example.com
          --admin_password=password
          --skip-email
      - name: Install Plugin from WordPress Directory
        run: >
          wp plugin install platforminfo
          --path=$WPROOT
          --force
          --activate
      - name: Run due cron events
        run: >
          wp cron event run
          --path=$WPROOT
          --due-now
      - name: Install Apache
        run: |
          sudo apt-get -y install apache2
          sudo apt-get -y install libapache2-mod-php
          sudo systemctl restart apache2.service
      - name: Test WP Response
        run: |
          curl http://localhost/wordpress/wp-cron.php
          curl http://localhost/wordpress/index.php
          wget --delete-after http://localhost/wordpress/wp-cron.php
          wget --delete-after http://localhost/wordpress/index.php