name: Plugin Build
on: [push, pull_request]
jobs:
  plugin-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer
      - name: Build the plugin into a zip file
        run: |
          composer install
          composer run build
          ls -al *.zip
