name: Static Analysis
on:
  push:
    paths:
      - '**.php'
      - 'psalm.xml'
      - 'composer.*'
jobs:
  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: pecl, composer
      - name: Static Analysis for PHP
        run: |
          php -v
          php -m
          composer install
          composer run analyse