name: Static Analysis
on: [push, pull_request]
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: redis
          tools: pecl, composer
      - name: Static Analysis for PHP
        run: |
          composer install
          composer run analyse